INSERT INTO exercise (exercise_name, exercise_type, exercise_major_muscle_group, exercise_minor_muscle_group, exercise_notes) VALUES
    ('Anti-Rotation','Weight','Core','Oblique','Keep your core tight and shoulders far from your ears.'),
    ('Arnold Press','Weight','Arms','Bicep, Shoulders',NULL),
    ('Battle Rope Wave','Plyo','Arms, Full Body','Shoulders',NULL),
    ('Battle Rope Wave + Burpee','Plyo','Full Body',NULL,NULL),
    ('Bench Press','Weight','Arms','Chest','Bar + 5LB'),
    ('Bicep Curl','Weight, Machine','Arms','Bicep','Don''t use momentum. Make sure the movement is coming from the bottom half of your arm not your shoulder moving the weight.'),
    ('Bicycle Crunch','Weight','Core',NULL,'The lower the "straight" leg is to the ground the more challenging this exercise is.'),
    ('Bounds','Cardio, Laps','Full Body, Legs','Outer Thigh, Glutes','Do laps across the room of these.'),
    ('Box Jumps','Plyo','Full Body',NULL,'Don''t be afraid, you can jump higher than you think. Just try it once.'),
    ('Box Toe Touch','Cardio','Legs','Glutes',NULL),
    ('Broad Jump','Plyo, Laps, Cardio','Legs','Glutes','You can do these for speed, or for distance. Speed = Cardio, Distance/Height = Plyo'),
    ('Bulgarian Split Squat','Weight','Legs','Hamstrings, Quads','Use Single 30LB Dumbbell or an Olympic Bar'),
    ('Burpee','Plyo','Full Body',NULL,'Option with half Bosu, Pushup Optional. Make sure you don''t round your back'),
    ('Burpee Broad Jump','Plyo, Laps','Full Body',NULL,'Do laps of these across the room if you have the space.'),
    ('Butt Kickers','Cardio','Legs','Glutes','Do it like you mean it, or this exercise is a waste of time.'),
    ('Cable Woodchop','Weight','Core',NULL,'The movement should originate from your core not your shoulders. The arms are just the vessel'),
    ('Calf Raise','Weight','Legs','Calves','Play around with foot placement, some gyms also have machines for this'),
    ('Chest Press','Weight','Arms','Chest','You can do this lying on the ground, or on a bench top'),
    ('Close to Wide Grip Burnout','Weight','Arms','Bicep',NULL),
    ('Compass Jump','Cardio','Full Body',NULL,'These can also be done with both feet on the ground.'),
    ('Crab Crawl','Cardio, Laps','Full Body',NULL,NULL),
    ('Curtsey Lunges','Weight','Legs','Inner Thigh',NULL),
    ('Deadlift','Weight','Legs','Hamstrings','Bar + 45LB'),
    ('Deficit Squat','Weight','Legs','Glutes',NULL),
    ('Donkey Kick','Weight','Legs','Glutes',NULL),
    ('Fire Hydrant','Weight','Legs','Glutes, Outer Thigh',NULL),
    ('Flutter Kick','Weight','Core',NULL,'Her neck looks like its undergoing some serious strain. Feel free to leave yours on the ground.'),
    ('Frogger','Plyo','Full Body',NULL,NULL),
    ('Front-Load Squat','Weight','Legs, Core','Glutes','Bar + 35LB'),
    ('Glute Bridge','Weight','Legs','Glutes','If using weights, place in hip crease'),
    ('Glute Bridge March','Weight','Legs','Hamstrings',NULL),
    ('Glute Kickback','Weight','Legs','Glutes',NULL),
    ('Goblet Squat','Weight','Legs','Glutes, Quads',NULL),
    ('Halo','Weight','Arms','Shoulders, Tricep',NULL),
    ('Hamstring Curl','Weight','Legs','Hamstrings',NULL),
    ('Heart Pump','Weight','Arms','Bicep, Chest',NULL),
    ('High Knees','Cardio','Full Body',NULL,'My coach always says, your high knees tells a lot about your dedication. Do yours like the guy in the gif. Get your knees up or don''t bother!'),
    ('Hip Thrust','Weight','Legs','Glutes','Bar + 35LB'),
    ('Incline Leg Press','Weight','Legs','Quads, Glutes',NULL),
    ('Jacknife','Weight','Core',NULL,NULL),
    ('Jump Lunges','Plyo, Cardio','Legs','Glutes, Quads',NULL),
    ('Jump Rope','Cardio','Full Body',NULL,NULL),
    ('Jumping Jack Push Press','Plyo','Full Body',NULL,NULL),
    ('Jumping Jacks','Cardio','Full Body',NULL,'Go faster than the gif lady. I chose her because she has good form, your hand should always touch at the top'),
    ('Kettlebell Swing','Cardio, Weight','Full Body',NULL,'When I do these I usually keep my hand close to my body and let my hips "push" the movement. If you''d like to experiment, you can use a dumbbell instead'),
    ('Knee Drive','Plyo','Full Body',NULL,NULL),
    ('L-Sit','Weight','Core, Arms','Shoulders',NULL),
    ('Lat Pulldown','Weight','Back','Lats',NULL),
    ('Lateral Band Walk','Cardio, Laps','Legs','Outer Thigh',NULL),
    ('Leg Pull Apart','Weight','Legs, Back','Outer Thigh',NULL),
    ('Leg Raise','Weight','Core',NULL,'Hold onto something heavy'),
    ('Literally Just Jumping','Plyo','Full Body','Calves, Glutes','No good gifs for this, keep core tight, minimize time on the ground and jump up and down.'),
    ('Lying Leg Raises','Weight','Core',NULL,NULL),
    ('Military Plank','Plyo','Full Body, Arms','Shoulders',NULL),
    ('Monkey Jump','Plyo, Cardio','Full Body',NULL,NULL),
    ('Mountain Climbers','Cardio','Core, Full Body',NULL,NULL),
    ('One-Arm Press','Weight','Arms','Shoulders',NULL),
    ('Pike to Superman','Weight','Core',NULL,NULL),
    ('Plank','Weight','Full Body, Core','Chest',NULL),
    ('Plank Jack','Cardio','Full Body, Core',NULL,NULL),
    ('Plank Row','Weight','Full Body, Back',NULL,NULL),
    ('Power Clean','Weight','Full Body',NULL,NULL),
    ('Pushup','Weight','Arms','Chest','Can be done from knees, or legs. Arms parallel to your body like the dude in the gif.'),
    ('Pushup Walk','Weight','Arms','Chest',NULL),
    ('Reverse Crunches','Weight','Core',NULL,NULL),
    ('Row','Weight','Back',NULL,'Bar + 15LB'),
    ('Russian Twist','Weight','Core',NULL,NULL),
    ('Seal Jacks','Cardio','Full Body',NULL,'Clap your hands and dance around while you do these. Makes life more fun.'),
    ('Seated Rope Pull','Weight','Core, Back',NULL,NULL),
    ('Shoulder Press','Weight','Arms','Shoulders','Bar + 5LB'),
    ('Side Arm / Lateral Raise','Weight','Arms','Lats',NULL),
    ('Side Lunge','Weight','Legs','Outer Thigh',NULL),
    ('Side Plank','Weight','Full Body, Core','Oblique',NULL),
    ('Side Plank Dips','Weight','Core','Oblique',NULL),
    ('Side Plank with Leg Lift','Weight','Core','Oblique',NULL),
    ('Single Arm Clean and Press','Weight','Full Body, Arms','Shoulders','Currently using 25LB'),
    ('Single Leg Hip Bridge','Weight','Legs','Hamstrings','You''re wasting your time on this if you''re not actually thinking about squeezing your glutes with each movement. You really need to be focused to do this.'),
    ('Single Leg Squat','Weight','Legs','Glutes, Quads',NULL),
    ('Situp and Throw','Weight','Core',NULL,NULL),
    ('Skaters','Cardio','Legs','Outer Thigh','Lady in the gif isn''t giving it 100% make sure to touch the ground between reps'),
    ('Skipping','Cardio, Laps','Full Body',NULL,NULL),
    ('Skull Crusher','Weight','Arms','Tricep',NULL),
    ('Spiderman Pushup','Weight','Arms, Core','Chest, Oblique',NULL),
    ('Squat','Weight','Legs','Quads, Glutes','Bar + 45LB'),
    ('Squat for Abductors','Weight','Legs','Outer Thigh, Inner Thigh','This is not proper use of this equipment, do this at your own risk!'),
    ('Squat Jump','Plyo, Cardio','Legs','Quads','You can do these for height (plyo) or speed (cardio) and to switch them up sometimes do them with your arms clasped at the front so it''s a leg-only exercise'),
    ('Squat Jumps 180','Plyo','Full Body',NULL,'Turn body 180 while doing squat jump'),
    ('Squat to Lateral Leg Lift','Weight','Legs','Quads, Outer Thigh',NULL),
    ('Stair Climber','Cardio','Legs','Glutes','Whatever you do, don''t slouch or rest your bodyweight on the handlebars while you do this. That''s just lazy. Maintain good posture. Hold weight while doing for extra challenge'),
    ('Standing Glute Kickbaks','Weight','Legs','Glutes',NULL),
    ('Standing Leg Lift','Weight','Legs','Inner Thigh, Outer Thigh, Glutes',NULL),
    ('Standing Oblique Crunch','Weight','Core','Oblique','20LB Weight Minimum'),
    ('Star Jump','Plyo','Full Body',NULL,NULL),
    ('Step Up Lunges','Plyo','Legs','Glutes',NULL),
    ('Step-Back Lunge','Weight','Legs','Glutes',NULL),
    ('Straightup Situp','Weight','Core',NULL,NULL),
    ('Sumo Squat','Weight','Legs','Inner Thigh, Outer Thigh','Bar + 35LB. You want your legs to be just wide enough that your knees still track over your toes'),
    ('Superman','Weight','Back',NULL,NULL),
    ('Thruster','Weight','Full Body',NULL,NULL),
    ('Touchdown','Plyo','Full Body',NULL,NULL),
    ('Tricep Dip','Weight','Arms','Tricep','Find a chair or platform you can lean on.'),
    ('Tricep Kick-Back','Weight','Arms','Tricep',NULL),
    ('Tricep Overhead Press','Weight','Arms','Tricep',NULL),
    ('Tricep Pull Down','Weight','Arms','Tricep','Keep your knees slightly bent as you do this'),
    ('TRX Mountain Climber','Weight','Core',NULL,NULL),
    ('TRX Plank','Weight','Core',NULL,NULL),
    ('TRX Row','Weight','Back',NULL,NULL),
    ('Tuck Jump','Plyo','Full Body',NULL,NULL),
    ('Twisted Mountain Climbers','Cardio','Full Body, Core','Oblique',NULL),
    ('V-Pass','Weight','Core',NULL,NULL),
    ('Wall Ball','Cardio','Full Body',NULL,'Toss the Medicine Ball in the air, or against a solid wall (concrete or brick) if available.'),
    ('Weighted Jumping Jacks','Cardio','Full Body',NULL,NULL),
    ('Weighted Machine Situp','Weight','Core',NULL,NULL),
    ('Weighted Punches','Cardio','Core',NULL,NULL),
    ('Deadbug','Weight','Core',NULL,'Really good if you have lower back pain and want to do an ab workout');
