INSERT INTO nutrition (food_name, food_type, food_calories, portion) VALUES
('mee rebus', 'main course', '558', 'plate'),
('mee siam', 'main course', '519', 'plate'),
('mee soto', 'main course', '432', 'bowl'),
('mee goreng', 'main course', '660', 'plate'),
('bak chor mee', 'main course', '511', 'bowl'),
('ban mian soup', 'main course', '475','bowl'),
('fried kway teow', 'main course', '743', 'plate'),
('hor fun', 'main course', '708', 'plate'),
('laksa', 'main course', '589', 'bowl'),
('fried beehoon', 'main course', '252', 'plate'),
('lor mee', 'main course', '383', 'bowl'),
('fishball noodles, dry', 'main course', '364', 'bowl'),
('fishball noodles, soup', 'main course', '330', 'bowl'),
('fish head beehoon soup', 'main course', '666', 'bowl'),
('sliced fish beehoon soup', 'main course', '349', 'bowl'),
('fried hokkien prawn mee', 'main course', '615', 'plate'),
('prawn noodles, dry', 'main course', '459', 'bowl'),
('prawn noodles, soup', 'main course', '293', 'bowl'),
('wanton noodles, dry', 'main course', '409', 'bowl'),
('wanton noodles, soup', 'main course', '217', 'bowl'),
('kway chap single serving', 'main course', '648', 'bowl'),
('chicken porridge', 'main course', '214', 'bowl'),
('fish porridge', 'main course', '261', 'bowl'),
('pork porridge', 'main course', '362', 'bowl'),
('century egg porridge', 'main course', '422', 'bowl'),
('char siew rice', 'main course', '600', 'plate'),
('duck rice', 'main course', '706', 'plate'),
('chicken rice', 'main course', '702', 'plate'),
('fried rice', 'main course', '508', 'plate'),
('nasi lemak', 'main course', '494', 'plate'),
('nasi briyani', 'main course', '880', 'plate'),
('fish and chips', 'main course', '848', 'plate'),
('grilled stingray', 'main course', '347', 'plate'),
('bak kut teh', 'main course', '342', 'bowl'),
('herbal black chicken soup', 'main course', '186', 'bowl'),
('tom yam seafood soup', 'main course', '271', 'bowl'),
('pig organ soup', 'main course', '158', 'bowl'),
('watercress and pork ribs soup', 'main course', '92', 'bowl'),
('chicken curry', 'main course', '450', 'bowl'),
('fish head curry', 'main course', '288', 'plate'),
('white bread', 'snack', '77', 'slice'),
('wholemeal bread', 'snack', '72', 'slice'),
('doughnut', 'snack', '304', 'piece'),
('char siew pau', 'snack', '212', 'bun'),
('chicken pau', 'snack', '204', 'bun'),
('pork pau', 'snack', '246', 'bun'),
('egg tart', 'snack', '177', 'piece'),
('ham chim peng', 'snack', '273', 'piece'),
('mee chiang kueh', 'snack', '186', 'piece'),
('roti prata plain', 'snack', '122', 'piece'),
('roti prata egg', 'snack', '289', 'piece'),
('roti john', 'snack', '571', 'piece'),
('carrot cake', 'main course', '467', 'plate'),
('oyster omelete', 'main course', '650', 'plate'),
('chee cheong fun', 'snack', '133', 'plate'),
('chwee kueh', 'snack', '57', 'piece'),
('curry puff', 'snack', '246', 'piece'),
('yam cake', 'snack', '174', 'piece'),
('you tiao', 'snack', '123', 'piece'),
('popiah', 'snack', '92', 'piece'),
('soon kueh', 'snack', '98', 'piece'),
('siew mai', 'snack', '105', 'piece'),
('otah', 'snack', '18', 'piece'),
('satay', 'snack', '35', 'stick'),
('rojak chinese', 'snack', '443', 'plate'),
('indian rojak', 'main course', '756', 'plate'),
('ice kacang', 'dessert', '257', 'bowl'),
('chendol', 'dessert', '593', 'bowl'),
('bubor cha cha', 'dessert', '390', 'bowl'),
('pulut hitam', 'dessert', '290', 'bowl'),
('tau suan', 'dessert', '293', 'bowl'),
('green bean soup', 'dessert', '237', 'bowl'),
('cheng tng', 'dessert', '257', 'bowl'),
('herbal jelly', 'dessert', '71', 'bowl'),
('coca cola', 'drink', '138', 'can'),
('sugar cane juice', 'drink', '158', 'cup'),
('bandung', 'drink', '153', 'cup'),
('soya bean drink', 'drink', '163', 'cup'),
('barley water', 'drink', '55', 'cup'),
('bubble tea with milk', 'drink', '232', 'cup'),
('bubble tea with pearls', 'drink', '340', 'cup')
